Plane XY
Plane XZ
Plane YZ
Elbow      
* * Can't convert "G54"
* * Can't convert "G61"
* * Can't convert "G61.1"
* * Can't convert "G64"
* * Can't convert "G64 P1"
* * Can't convert "G04 P1.0"
* * Can't convert "N100 G04 P2"
Line       X 1.0000 Y 1.0000 Z 1.0000 Feed 10.0000  ToolComp Off
Feed 10.0
Line       X 0.2000 Y 3.0000 
Line       Z 4.0000 
Dim Abs
Unit MM
Plane XY
* * Can't convert "G54"
* * Can't convert "G90 G21 G17 G54"
* * Can't convert "G59"
* * Can't convert "G59.1"
* * Can't convert "G59.2"
* * Can't convert "G59.3"
* * Can't convert "G54"
* * Can't convert "G10 L1 P1 R1.5000 Z15.00"
Line       X 1.0000 Y 1.0000 
Feed 10.0
Rapid      X 1.0000 Y 2.0000 
Feed 15.0
* * Can't convert "G73 Z-1.0 F10.0 Q0.20 R0.10"
DrillOff
BasicDrill ZDepth 1.5000 StartHgt 0.0000 
DrillOff
* * Can't convert "G82 X4 Y5 Z1.5 R0 P1"
DrillOff
PeckDrill  ZDepth -1.0000 StartHgt 0.1000 Feed 10.0000 
DrillOff
Line       X 1.0000 Y 1.0000 Z 1.0000 
Dwell 3.0
Line       X 1.0000 Y 1.0000 Z 2.0000 
Dim Abs
Dim Incr
Dim Abs
Dim Incr
MCode 0
